name: Run tests
run-name: Run tests
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: env
      - run: npm install -g bats
      - name: BATS tests
        run: bats test
      - name: E2E tests
        run: |
          for test_script in test/e2e/test_e2e_load_library*; do
            echo "Running $test_script"
            bash -x $test_script || exit 1
          done
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: './src'
