name: Run tests
run-name: Run tests
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - name: BATS tests
        run: bats test
      - name: E2E tests
      - run: |
        for test_script in test/e2e/test_*; do
            $test_script || exit 1
        done
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: './src'
